public/coffee/ide/pdf/controllers/PdfController.coffee, public/coffee/ide/pdfng/directives/pdfRenderer.coffee, public/coffee/ide/pdfng/directives/pdfViewer.coffee
Catch errors from pdfjs where possible, and use a 60 second timeout to kill pdfjs and force reload of document if page does not load or render.
If document has to be reloaded more than twice, show the "Compile failed message" so user has to click recompile manually.
=> Pdfng reload on error

public/coffee/ide/pdfng/directives/pdfRenderer.coffee
For compatibility with pdfListView  I think we should switch back to using the browser font renderer to display the pdf.  It is a slower on rendering for figures, but does give nicer looking anti-aliased text.
=> use font-face for pdfjs rendering

public/coffee/ide/pdfng/directives/pdfPage.coffee, public/coffee/ide/pdfng/directives/pdfRenderer.coffee, public/coffee/ide/pdfng/directives/pdfViewer.coffee
To improve the scrollhandler performance there were several stages
- remove all per-page watchers and put the visibility calculation in the top-level viewer
- use setTimeout in the scrollhandler instead of $timeout (the latter triggers a digest which is expensive)
- in the visibility calculation use DOM methods to get positions instead of Jquery (this loop is executed a lot)
- debouce scroll events, so scrollhandler fires 25ms after user stops scrolling
- remove useless scope.apply's, since these trigger a digest
=> Pdfng scrollhandler performance improvements

public/coffee/ide/directives/layout.coffee, public/coffee/ide/editor/controllers/SavingNotificationController.coffee, public/coffee/ide/editor/directives/aceEditor/highlights/HighlightsManager.coffee, public/coffee/ide/editor/directives/aceEditor/spell-check/SpellCheckManager.coffee, public/coffee/ide/pdfng/directives/pdfJs.coffee, public/coffee/ide/pdfng/directives/pdfRenderer.coffee, public/coffee/ide/pdfng/directives/pdfViewer.coffee
Add missing scope.apply's needed to fix up the new pdf viewer when there are no digests running in the background.  
Now queues redraws/relayouts so they only occur once.
=> Fix pdfng no background digests

public/coffee/ide/directives/layout.coffee, public/coffee/ide/editor/controllers/SavingNotificationController.coffee, public/coffee/ide/editor/directives/aceEditor/highlights/HighlightsManager.coffee, public/coffee/ide/editor/directives/aceEditor/spell-check/SpellCheckManager.coffee
Avoid calling scope.$apply in the following cases
- editor highlights (on mousemove in editor)
- closing context menu (on scroll in editor)
- background saved file check (every second)
Also fixes attrs.layoutDisabled watch on undefined.
=> Fix performance

public/stylesheets/app/editor/binary-file.less
Trying to fix issue #124.
I set overflow in auto mode to allow large images. It seems to be the simplest way and the expected site comportment.
=> Allowed scroll on binary-file container

app/coffee/Features/Compile/ClsiManager.coffee, app/coffee/Features/Compile/CompileController.coffee, public/coffee/ide/pdf/controllers/PdfController.coffee, test/UnitTests/coffee/Compile/ClsiManagerTests.coffee, test/UnitTests/coffee/Compile/CompileControllerTests.coffee
Use the build identifier provided by the CLSI to request output files from a specific build.
Should prevent output files from changing while they are being downloaded.
=> Support cached pdfs with build parameter

public/coffee/ide/editor/directives/aceEditor/spell-check/SpellCheckManager.coffee
Adds [Latin Extended-A](https://en.wikipedia.org/wiki/Latin_Extended-A) characters to word regex to prevent splitting words half way through on characters like ąęćółżźńś.
Should close issue #58.
=> Update word regex for spellcheck

app/views/project/editor.jade, public/coffee/ide/editor/Document.coffee, public/coffee/ide/editor/EditorManager.coffee, public/coffee/ide/editor/ShareJsDoc.coffee, public/coffee/ide/editor/sharejs/vendor/client/doc.coffee, public/coffee/ide/pdf/controllers/PdfController.coffee
Add in 5 second delay between flushing updates when only a single user
is editing a document. As soon as an update is received from another user
we switch to sending updates immediately again so there is no latency
between collaborators. The logic applies to individual docs, so two users
can be editing different docs and will still buffer updates since they
will not affect each other.
=> Buffer updates when only a single user is editing a document

app/views/project/editor.jade
Use a requirejs shim to make sure ace language tools have ace already loaded.
Have checked the source with git grep to make sure searchbox and language tools are the only two modules we are currently using.
=> prevent loading error for ace language tools extension in development

app/coffee/Features/Compile/CompileController.coffee, app/coffee/Features/FileStore/FileStoreHandler.coffee, app/coffee/Features/Link/LinkController.coffee, app/coffee/Features/Link/LinkCreator.coffee, app/coffee/infrastructure/Mongoose.coffee, app/coffee/infrastructure/Server.coffee, app/coffee/models/Link.coffee, app/coffee/router.coffee, app/views/project/editor/link-image.jade, app/views/project/editor/output_panel/script_output.jade, config/settings.defaults.coffee, package.json, public/coffee/ide.coffee, public/coffee/ide/link-image/controllers/LinkImageController.coffee, public/coffee/ide/link-image/controllers/LinkImageModalController.coffee, public/coffee/ide/link-image/index.coffee, public/stylesheets/app/editor/output.less
Add support for short urls for sharing images.  
To create a link post the url to /project/:project_id/lin
The urls have the form www.getdatajoy.com/public/sk212a/foo.png
They are stored in the filestore under a separate s3 bucket
The filestore has been modified to accept  REST requests of the form project/:project_id/public/:public_file_id
=> allow public sharing of images via urls

package.json
I'm installing a development environment and came across some build errors while installing bcrypt. Looking at the [bcrypt website](https://www.npmjs.com/package/bcrypt) I found out that the current version would not work on nodejs newer than 0.10. As people will probably use the latest nodejs when installing sharelatex, probably they will face the same problem I did.
Also, may be interesting to set the nodejs supported version in the [installation wiki page](https://github.com/sharelatex/sharelatex/wiki/Setting-up-a-Development-Environment).
This new version compiles successfully on nodejs newer than 0.10.
=> Update bcrypt to 0.8.3

app/views/project/editor/left-menu.jade
The word count window does the wrong alignment (as you can see in the picture) if the window width is less than the bootstrap `md` size (992px).
=> Correct alignment for word count dialog

app/views/project/editor/left-menu.jade, app/views/project/editor/pdf.jade, public/coffee/ide/pdf/controllers/PdfController.coffee
Fix the pdf downloads so that the project name is used as the filename again.
Define a separate pdf.downloadUrl which uses the /Project/ route that adds a content-disposition with the project name.
=> fix filename of downloaded pdf files

public/coffee/ide/pdf/controllers/PdfController.coffee, public/coffee/ide/pdfng/directives/pdfJs.coffee, public/coffee/ide/pdfng/directives/pdfViewer.coffee
Synctex position was inverted when clicking the goto code button.
Changed the parameters to align to visual offsets for going forwards and backwards) (if you go to pdf and back to code you get to the same place)
=> Fix synctex position calculation

app/coffee/Features/Compile/CompileController.coffee, app/coffee/Features/Compile/CompileManager.coffee, config/settings.defaults.coffee, public/coffee/ide/pdf/controllers/PdfController.coffee, public/coffee/ide/wordcount/controllers/WordCountModalController.coffee, test/UnitTests/coffee/Compile/CompileControllerTests.coffee, test/UnitTests/coffee/Compile/CompileManagerTests.coffee
don't require the client to send ?isolated=true
can override with Settings.disablePerUserCompiles:true
=> remove scaffolding for per-user compiles so that it is always by default

app/coffee/Features/Compile/CompileController.coffee
allow synctex paths containing /./ through file check
=> work around for synctex paths containing /./

app/coffee/infrastructure/Server.coffee
- only evaulate close on web router, not api/static assets
- allow /admin pages to still be available
=> fix close editor button

app/views/layout.jade, public/coffee/ide.coffee, public/coffee/ide/pdf/controllers/PdfController.coffee, public/coffee/ide/share/controllers/ShareController.coffee, public/coffee/main/event.coffee
Diminish the amount of data being sent to Countly:
- Don't track page views
- Don't track sessions
- Track a few events only the first time they happen for a given user (we only want to know it happened once, not the amount/frequency).
=> Countly pruning

public/coffee/ide.coffee, public/coffee/ide/SafariScrollPatcher.coffee
This PR adds a workaround for the misplaced scroll behaviour (in Safari).
Problem: scroll (`wheel`) events were being sent to the PDF preview (built-in), while the mouse pointer was hovering the editor. Something is causing Safari to miscalculate each element's region.
Solution: listen to `wheel` events bound to the PDF preview while the mouse is *not* hovering it, then dispatch it to the editor (if it's being hovered).
=> Workaround for safari scrolling bug

app/views/subscriptions/plans.jade
Hide sign up button via CSS visibility (to keep the layout sizing), if the user is logged in.
=> Hide "sign up" button in plans page, if user is logged in

app/coffee/Features/Compile/ClsiCookieManager.coffee, app/coffee/router.coffee
use a valid user id, report all failures as errors, clear timeout on success
=> clean up compile check

public/coffee/ide/pdfng/directives/pdfRenderer.coffee
font-face rendering in pdfjs doesn't work properly in Microsoft Edge at the moment.
=> disable pdfjs fontface on Microsoft Edge

app/views/project/editor/editor.jade, public/coffee/ide/editor/EditorManager.coffee, public/coffee/ide/editor/directives/aceEditor.coffee
Ace has an extension for detecting modes from filenames.  We can use it to get full support for all file types.
Also, the mode only needs to be set once when the session is created.  This avoids unnecessary work as setting the mode multiple times can create a worker each time, even when one already exists.
=> use ace mode detection

public/coffee/ide/connection/ConnectionManager.coffee
- fix change of lastUpdated to lastUserAction to correctly reduce connect rate after 2 minutes
- apply rate limit to reconnect attempts from cursor movement (fires rapidly)
- use socket.socket.connect() instead of socket.socket.reconnect() to avoid socket.io retrying in the background
=> rate limit on reconnects

app/views/project/editor.jade, public/coffee/ide/editor/controllers/SavingNotificationController.coffee, public/coffee/ide/services/ide.coffee, public/stylesheets/app/editor.less
block access to the editor after 15 seconds of unsaved changes.
reconnect attempts continue in the background.
=> lock editor when connection down

app/views/project/editor/editor.jade, public/coffee/directives/asyncForm.coffee, public/coffee/main/account-settings.coffee, public/coffee/modules/errorCatcher.coffee
if the user gets a 401 or 403 on any http request while using the editor we redirect them to /login
exceptions for asyncForm and delete account
also turn off spelling for anonymous users, because it always fails the auth check
=> redirect to login on 403

app/coffee/Features/Email/EmailSender.coffee
This fixed a problem I was having with sending password reset emails via SMTP port 25 on a server that supports STARTTLS, but on which I did not want to use STARTTLS.
Without this change I would get a "CERT_UNTRUSTED" error, and nodemailer never sees the ignoreTLS option set in the environment.
=> Pass ignoreTLS option to nodemailer

public/coffee/main.coffee
Disable angular hijacking `#` links.
This specifically un-breaks the behaviour of `#` links in the learn pages.
=> Sk learn anchor links

app/coffee/infrastructure/ExpressLocals.coffee, app/views/layout/navbar.jade, config/settings.defaults.coffee
Move auth parts of top menu out of config and into web templates.
Move the remaining configuration into a new config var: `nav.header_extras`.
Add a `nav.showSubscriptionLink` var to control visibility of subscription link
in the Account menu.
This will allow admins to more easily configure extra links in the top
navigation bar, without the danger of overwriting the important auth menus.
=> Sk top menu rework

public/stylesheets/app/editor/review-panel.less
Disabled buttons seemed to have a border-bottom. This was because opacity somehow changed the rendering mode. Solution was to precompute the tinted color, instead of using opacity.
=> Use solid color instead of opacity, to avoid rendering issues.

public/stylesheets/app/editor/review-panel.less
Controlling overflowing content (in this case, a textarea which expands with content) seems to fix the issue.
=> Avoid blank screen bug, when triggered by very large comments.

public/coffee/ide/directives/layout.coffee
* Set the synctex controls to a lower z-index value (was 10, which doesn't seem necessary; 3 seems to be enough);
* Patch the overflowing behaviour in the center (editor) pane. Default overflow would put the pane exactly at the same z-index level than the synctex controls. The latter (as it appears "after" in the DOM) would then be "on top" of the former. Patch ensures that the center pane's z-index is incremented by one.
P.S. Overflowing behaviour, in a jQuery layout context, means that an element is configured to allow child elements to overflow it (e.g. pop-ups, such as the review entries). This is what we want in the center pane.
=> z-index syntax & review panel

app/views/project/editor/review-panel.pug, public/coffee/ide.coffee, public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee, public/stylesheets/app/editor/review-panel.less
This PR adds an AB test on the "Add comment" button. Only new users should participate.
* Default variation is as a review panel entry;
* B variation is a button in the top-right corner of the editor.
This PR also fixes an issue where the editor scrollbar would hide items in the top-right corner of the editor (not only the new button, but also the "track changes is on" indicator).
TODO: Before merging, change the sign-up date verification.
=> PR AB test "add comment" button

app/coffee/Features/Subscription/RecurlyWrapper.coffee, app/coffee/Features/Subscription/SubscriptionController.coffee, app/coffee/Features/Subscription/SubscriptionHandler.coffee, test/UnitTests/coffee/Subscription/SubscriptionControllerTests.coffee, test/UnitTests/coffee/Subscription/SubscriptionHandlerTests.coffee
Previously, we have assumed Mongo was a reliable indicator of subscription state. Occasionally there is a subscription in Recurly not reflected in Mongo. So we now check Recurly as well before creating a new subscription (both on showing the page, and actually doing the create). If there is one then we didn't expect it, which means it's not in Mongo, so we sync it.
=> Check Recurly for subscription as well before creating subscription

app/coffee/Features/Email/EmailSender.coffee, test/UnitTests/coffee/Email/EmailSenderTests.coffee
This prevents us from leaking juicy details of our aws/ses setup via the
password-reset form.
=> If sending email fails, return a generic error.

public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee
Resolved threads retrieved from the server use strings to represent the resolution date, while threads resolved in the current session are stored locally using a Date type. This caused Angular ng-repeat to misorder resolved threads; solution was to enforce the same data type (ISO date strings) in the locally resolved threads.
=> Use ISO strings instead of of date type in locally resolved comments.

app/views/project/editor/header.pug, public/coffee/ide/settings/controllers/ProjectNameController.coffee, public/stylesheets/app/invite.less
Currently, project name is truncated at 250px, which doesn't allow users to see the full name. This PR adds a tooltip to the project name in the editor header, showing the full project name. 
Tooltip should only be triggered if the project name is long enough to be truncated.
=> Project name tooltip

app/views/project/editor/feature-onboarding.pug
During Angular template compilation, HTML is interpreted "as is" by the browser. In Firefox, this means that video elements might prompt downloading and decoding of media assets, even though they end up being removed via falsy `ng-if`s after Angular compilation.
This fix uses `ng-src` instead of plain `src`; this means that the `src` attribute is only set after Angular compilation occurs and only if the element is to be shown.
=> Set video source only when the onboarding prompt is shown.

public/js/ace-1.2.5/ace.js
Ace's custom character composition logic seems to be faulty on new versions of Safari, similarly to what happens in Chrome since version 53. It can be fixed by applying Chrome's workaround to Safari as well. Issue was created in Ace's repo: https://github.com/ajaxorg/ace/issues/3257
Safari detection logic was also added to Ace's useragent lib (it wasn't available before). To keep the API consistent, `isSafari` property works like the existent `isChrome`: if the browser is detected, it returns a float with the version number; otherwise, returns `undefined`.
=> Fix safari accent handling

app/views/project/list.pug
We currently JSON encode the data, but then let the browser parse it as javascript. This trips up when there are certain unicode symbols in the project name. If we properly pass it as JSON and then explicitly parse it again client side, then it is ok. We perhaps need to do a more systematic audit of how we pass data to the client, since we have no consistent pattern, and we want to be able to fix things like this everywhere in one go.
=> Properly pass project data as JSON and then parse it

app/views/project/editor.pug, public/coffee/ide/connection/ConnectionManager.coffee
socket.io seems to choke on the unicode project name and just return
undefined when it fails to parse the JSON. I've improved the escaping
of the user data on HTML load, but reporting an error is the best we
can easily do on joinProject via websockets.
=> Error if no project returned from joinProject

app/coffee/Features/Docstore/DocstoreManager.coffee, test/UnitTests/coffee/Docstore/DocstoreManagerTests.coffee
handling missing docs by returning 404 to to make it easier to debug errors in the stack
=> return 404 for api request on missing doc

public/coffee/ide/editor/directives/aceEditor/track-changes/TrackChangesManager.coffee, public/coffee/ide/review-panel/RangesTracker.coffee, public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee
Mostly code to prepare https://github.com/sharelatex/web-sharelatex/pull/498 
Some clients might have outdated code bundles in the front-end (cache), making them unable to process the new socket events added in the PR above. This PR—to be merged beforehand—will ensure that clients will at least be able to handle the new events (i.e. receive remote bulk actions).
=> Prepare bulk actions events

app/coffee/Features/FileStore/FileStoreHandler.coffee, test/UnitTests/coffee/FileStore/FileStoreHandlerTests.coffee
avoid potential double callbacks when uploading files
don't start the upload to s3 unless the file is opened successfully
=> improve stream error handling on upload

app/coffee/Features/Compile/ClsiCookieManager.coffee, test/UnitTests/coffee/Compile/ClsiCookieManagerTests.coffee
ioredis returns "" for a blank entry, the previous driver returned null,
so also check for a blank string
=> Check for blank string in clsi cookie caching

app/views/project/editor/editor.pug, app/views/project/editor/hotkeys.pug, app/views/project/editor/review-panel.pug, public/coffee/ide/editor/directives/aceEditor.coffee, public/coffee/ide/hotkeys/controllers/HotkeysController.coffee, public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee, public/stylesheets/app/editor/review-panel.less
This PR adds:
* The ability to hide the review panel when clicking on the left border + a little arrow (like in the other panel splitters)
* Keyboard shortcuts for review features
* Cmd/Ctrl + J to toggle the review panel
* Cmd/Ctrl + Shift + A to toggle track-changes on or off
* Cmd/Ctrl + Shift + T to add comments
* (Adds the keyboard shortcuts to the hotkeys modals and re-arranges it—it was getting too small)
=> Hide review panel+keyboard shortcuts for review

public/coffee/ide/pdfng/directives/pdfRenderer.coffee
This reverts commit f270ef54911acd800d2ffd577080b50ea2fe4aff.
Use a new worker on each reload to free up memory.
Keeping the worker was using more memory and not making the rendering any faster.
=> Revert "use a single pdfjs worker, rotated to avoid leaks"

public/coffee/ide/pdfng/directives/pdfViewer.coffee, public/stylesheets/app/editor/pdf.less, public/stylesheets/app/editor/toolbar.less
this needs some work, as we would like to select text across multiple pages -- as is currently possible,
but the scrolling is MUCH faster
=> set text layer to display:none for faster scroll

app/views/sentry.pug
This should allow app to continue to work if loading Raven
times out.
=> Add an error handler to Raven loader.

app/views/project/list/side-bar.pug
Sorts the ordering of tags—we were using 'name' as a variable, not as a property.
=> Fix typo in ng-repeat directive.

app/views/contact-us-modal.pug, public/coffee/main/contact-us.coffee
If we send a ticket to groove without either a subject, email or body, it rejects it. However, we had no error handling on the response from Groove, so this would be silently ignored, and the user told that their request had been submitted.
=> Validate and add error status to contact form

public/coffee/main/project-list/project-list.coffee
Some users complained about the number of uncategorized projects not matching what they expected (e.g. UI shows 4 uncategorized projects, but there are none). This was because the number of uncategorized projects was including deleted projects; this PR changes the "counting" method.
=> Correct count of uncategorized projects

app/coffee/infrastructure/ExpressLocals.coffee, app/views/project/editor/editor.pug, npm-shrinkwrap.json, package.json
When used inside Angular-evaled attributes, translations can break the templates (by e.g. including a single-quote). This error will then potentially occur for every user in a given problematic language, which will then clutter Sentry with [Angular Lexer Errors](https://docs.angularjs.org/error/$parse/lexerr).
1. Go to sharelatex.com and change the language to French;
2. Open a project and compile it;
3. Hover the "Go to PDF location in code" button.
This will trigger errors in the dev console, and the button tooltip won't work (however, it works in the button above).
Solution was to add a third optional parameter (defaulting to `false`)  to the `translate` Express local. This parameter, when `true`, will HTML encode the string (avoiding problematic characters such as the single quote). …
=> Support HTML encoded i18n

app/views/project/editor.pug, public/coffee/ide/pdfng/directives/pdfRenderer.coffee
In v1.8.188 of PDF.js, fetching Cmaps was [refactored](https://github.com/mozilla/pdf.js/pull/8064) and moved the implementation out of the worker thread. This meant that the URL's relative path changed from `/js/libs/pdfjs-VERSION/` to the project root, breaking Cmap fetching. This PR fixes by providing the correct relative path to the Cmaps directory.
=> Fix Cmaps path for future versions of PDF.js

app/coffee/infrastructure/ExpressLocals.coffee
Need to add ol-style to the fingerprint list - we're getting a lot of errors "No fingerprint for file: /stylesheets/ol-style.css"
=> add ol-style.css to fingerprint list

app/coffee/Features/Compile/ClsiManager.coffee, app/coffee/Features/Compile/ClsiStateManager.coffee, test/UnitTests/coffee/Compile/ClsiManagerTests.coffee, test/UnitTests/coffee/Compile/ClsiStateManagerTests.coffee
only do incremental compiles when the compile options are the unchanged (to prevent problems where the compile options affect the input files, e.g. when we do some rewriting in the clsi)
=> include the options in the project state hash

app/coffee/Features/Email/EmailSender.coffee
This allows end-users to use AWS features such as instance roles,
avoiding the use of explicit crendentials
=> Instantiate the ses client if explicitly specified.

app/views/project/editor/share.pug, public/coffee/ide/share/controllers/ShareProjectModalController.coffee
This fixes a few UX issues in the email autocompletion:
- Pressing enter with a partially completed email would not select the suggestion, but insert the partial email address
- Users who had not set a last name would see `undefined` as the suggested user's name
- Submitting an invalid email to the server would not show a useful error message
[GIF!](https://user-images.githubusercontent.com/424411/30114367-94817692-930f-11e7-9096-b0c2ee0126a0.gif)
https://github.com/overleaf/sharelatex/issues/66
The error message I went with was "An email address is invalid". This is a bit ambiguous, but due to the way in which we submit emails, we can only be sure about 1 invalid email (and there may be multiple submitted). We should look into refactoring this in the future.
=> Fix UX issues in email autocompletion in share modal

public/coffee/ide/pdf/controllers/PdfController.coffee
Extends #591. Improves auto-compile by checking last recompile time instead of a simple debounce. This means users doing "infrequent edits" will trigger an auto-compile faster, without waiting for the debounce timer to expire.
⚠️ Base branch is `as-client-autocompile`, not `master`. Once #591 is merged, will change to `master`.
=> Improve "infrequent edit" auto compile UX

app/coffee/Features/Compile/ClsiManager.coffee, public/coffee/ide/pdf/controllers/PdfController.coffee
to allow recovery from problems in the incremental updates, do a full compile after any server error from the clsi or error getting incremental files from the docupdater.
Currently, if there is an error from either of those we keep trying the incremental request - with no way for the user to recover.
=> suppress incremental compile after errors

app/coffee/infrastructure/Server.coffee, npm-shrinkwrap.json, package.json, test/acceptance/coffee/SecurityHeadersTests.coffee
Adds a bunch of security headers to better protect the app from some attacks.
This uses the [Helmet package](https://helmetjs.github.io/docs/) see the documentation for more details about each headers.
- `X-DNS-Prefetch-Control`
I don't see any good reason to disable prefetching
- `X-Frame-Options: SAMEORIGIN`
- `Strict-Transport-Security: max-age=15552000; includeSubDomains`
- `X-Content-Type-Options: nosniff`
No impact expected.
- disable `X-Powered-By`
- `X-Download-Options: noopen`
already used on OL
- `X-XSS-Protection: 1; mode=block`
already used on OL
Potential Impact: low, should only block features we don't use.
- `Surrogate-Control: no-store` 
- `Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate` (already used on OL)
- `Pragma: no-cache` 
- `Expires: 0` …
=> Add security headers

app/coffee/infrastructure/Server.coffee, test/acceptance/coffee/SecurityHeadersTests.coffee
Don't add `Strict-Transport-Security`, `X-Content-Type-Options` and `X-Frame-Options` headers.
=> Remove extra security headers

app/coffee/Features/Compile/ClsiManager.coffee, app/coffee/Features/DocumentUpdater/DocumentUpdaterHandler.coffee, test/UnitTests/coffee/Compile/ClsiManagerTests.coffee, test/UnitTests/coffee/DocumentUpdater/DocumentUpdaterHandlerTests.coffee
call the endpoint in the docupdater to clear the project state when the user clicks the trash can, allows us to recover if the state is out of sync.
=> clear docupdater project state in deleteAuxFiles

public/coffee/ide/editor/directives/aceEditor/auto-complete/CommandManager.coffee
Also, since there are a few Greek letters in the top 100, I thought for completeness we should all them all. (Note: I omitted commands in the top 100 if they require a package to be loaded e.g. `mathcal`).
=> adding commands that appear in top 100 from SL-CLSI analysis

public/coffee/ide/editor/directives/aceEditor/auto-complete/CommandManager.coffee
This allows editor to pick up more than 100 commands (previous limit) used in files. Now bumped up to 5000.
=> Raising the limit on safari regex count

app/src/Features/Project/ProjectController.js, app/src/infrastructure/ExpressLocals.js, app/views/layout.pug, app/views/project/list.pug, test/unit/src/Project/ProjectControllerTests.js
The messages are displayed above the project list only.
There is no need to query the system messages from ALL the other routes,
e.g. for compile requests.
Note: the admin view uses the same variable, but injects an uncached
value into the template. [1]
https://github.com/overleaf/web/pull/699
High, all routes ran through this middleware
cc @ShaneKilkelly 
---
[1] https://github.com/overleaf/web/blob/4c4fd1e8fcef940fda422d90e3d02e06f73a5774/app/src/Features/ServerAdmin/AdminController.js#L96-L99
=> [perf] lookup system messages from the project-list route only
