app/views/project/editor/output_panel/script_output.jade
public/coffee/ide/script-output/ScriptOutputManager.coffee
public/coffee/ide/script-output/directives/stackFrame.coffee
public/coffee/ide/services/commandRunner.coffee

detect R error messages/stack traces and provide buttons to jump to the source of the error.
Also highlights errors in ace border.

add R error message support

---

public/coffee/ide/services/commandRunner.coffee

handle python error messages in the commandRunner

Add support for python error messages

---

app/coffee/Features/HealthCheck/HealthCheckController.coffee
test/smoke/coffee/SmokeTests.coffee

Allows the module to be garbage collected.

port leak fixes from smoke-test-sharelatex module

---

app/coffee/Features/Subscription/SubscriptionGroupController.coffee
app/coffee/Features/Subscription/SubscriptionRouter.coffee
app/views/subscriptions/group_admin.jade
test/UnitTests/coffee/Subscription/SubscriptionGroupControllerTests.coffee

New feature to export users of a subscription group for a csv file (email only)

Group Csv Export

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/coffee/Features/Compile/CompileManager.coffee
app/coffee/router.coffee
app/views/project/editor/binary-file.jade
app/views/project/editor/file-tree.jade
public/coffee/ide/binary-files/BinaryFilesManager.coffee
public/coffee/ide/file-tree/FileTreeManager.coffee
public/coffee/ide/file-tree/controllers/FileTreeController.coffee
public/coffee/ide/file-tree/controllers/FileTreeEntityController.coffee
public/coffee/ide/file-tree/controllers/FileTreeRootFolderController.coffee
public/coffee/ide/services/jupyterRunner.coffee

Display a flat list of output files in the file true, and allow output files to be deleted by the user.

Datajoy show output files

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/coffee/Features/Compile/CompileManager.coffee
app/coffee/router.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee
test/UnitTests/coffee/Compile/CompileControllerTests.coffee
test/UnitTests/coffee/Compile/CompileManagerTests.coffee

Add wordcount clsi handler to web repo

Wordcount hook

---

public/js/libs/latex-log-parser.js

Added a single function to handle all package warnings, either one-line or multi-line, and finding the correct line number if any. The function takes advantage of the fact that LaTeX inserts a blank line after each warning.
The main changes are:
* Modified the parser to include the string **Package (packagename) Warning:**, this makes it easier to figure out what is causing the warning, specially when there's no line number.
* Added tests for the *geometry* package.
* Added tests for the *caption* package. Warnings from this one are hard to parse because the second line has a *(caption)* prefix and also includes the source-file line number, and the last line doesn't have blank spaces at the beginning.

Updated package warning parser

---

app/coffee/Features/Notifications/NotificationsController.coffee
app/coffee/Features/Notifications/NotificationsHandler.coffee
app/coffee/Features/Project/ProjectController.coffee
app/coffee/router.coffee
app/views/project/list.jade
app/views/project/list/notifications.jade
config/settings.defaults.coffee
public/coffee/main/project-list/index.coffee
public/coffee/main/project-list/notifications-controller.coffee
public/coffee/main/project-list/project-list.coffee
test/UnitTests/coffee/Notifications/NotificationsControllerTests.coffee
test/UnitTests/coffee/Notifications/NotificationsHandlerTests.coffee
test/UnitTests/coffee/Project/ProjectControllerTests.coffee

Initial PR to Notification Web Module for ShareLaTeX

Notifications Web Module

---

app/views/project/editor/editor.jade
public/coffee/ide/editor/directives/aceEditor.coffee
public/coffee/ide/editor/directives/aceEditor/spell-check/SpellCheckManager.coffee

cache the last 1,000 words so that updates when typing will mostly be cached (the same line is sent to the server each time, with the addition of the latest word typed).

add client-side spelling cache to reduce load on server

---

app/coffee/Features/Compile/CompileController.coffee
app/coffee/router.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee

client now requests output files using /project/project_id/build/build_id/output/*

Add fast path to pdf

---

public/coffee/ide/pdf/controllers/PdfController.coffee

simplify the log request code, only request the output.blg file when present in the list of output files

clean up log requests, avoid requesting blg file when not present

---

app/coffee/Features/Compile/CompileController.coffee
app/coffee/router.coffee

Filter syntex requests,  add support for passing additional query string to proxy request to clsi

Add query string to proxy and filter synctex requests

---

app/coffee/Features/Compile/ClsiManager.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee

use path attribute sent back by clsi

Per user containers part 0

---

app/coffee/Features/Compile/ClsiManager.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee

use url attribute sent back by clsi

Per user containers part 1

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/coffee/Features/Compile/CompileManager.coffee
app/coffee/router.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee
test/UnitTests/coffee/Compile/CompileControllerTests.coffee
test/UnitTests/coffee/Compile/CompileManagerTests.coffee

add per-user compilation in server and client, enabled by ?isolated=true

Per user containers part 2

---

public/coffee/ide/pdf/controllers/PdfController.coffee

turn on the isolated flag for all users

enable per-user containers by default

---

app/coffee/Features/Compile/CompileController.coffee
app/coffee/router.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee

fix the download links in the per-user containers

Fix per user containers

---

app/coffee/Features/Authentication/AuthenticationManager.coffee
config/settings.defaults.coffee
test/UnitTests/coffee/Authentication/AuthenticationManagerTests.coffee

check the number of rounds on login, and set the password again (with a higher number of rounds) if necessary

use parameter for bcrypt rounds, rehash passwords on login if necessary

---

public/coffee/ide/pdfng/directives/pdfRenderer.coffee
public/coffee/ide/pdfng/directives/pdfViewer.coffee

enable on demand viewing only when ?isolated=true

add support for on-demand viewing of pdfs for per-user compiles 

---

app/views/layout.jade
app/views/project/editor/editor.jade
app/views/project/editor/pdf.jade
public/coffee/ide.coffee
public/coffee/ide/hotkeys/controllers/HotkeysController.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee
public/coffee/ide/settings/services/settings.coffee
public/coffee/ide/share/controllers/ShareController.coffee
public/coffee/main/event.coffee

- Integrates Countly script and setup;
- Adds event tracking (mostly in the editor);
- Removes heap from client-side code.

Countly integration

---

public/coffee/ide/pdf/controllers/PdfController.coffee
public/coffee/main/event.coffee

Add a method to randomly sample events (1%); integrate said method with editor recompiles.

Sampled Countly tracking

---

public/coffee/ide/pdf/controllers/PdfController.coffee

Track positive and negative feedback as different events, for easier analysis.

Track positive and negative feedback as different events

---

public/coffee/ide/pdf/controllers/PdfController.coffee
public/coffee/main/account-upgrade.coffee
public/coffee/main/new-subscription.coffee

Track trial starts, with source. Also track the subscription form flow (enter the subscription form, submission tentative and submission success).

Track trial start and subscription

---

app/views/layout.jade

- Set feature flags, whenever they're available (typically, in the editor page);
- Use built-in Countly property to set user id (instead of calling a `change_id` event);
- Refactor user-data related code into a single script block.

User segmentation

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/coffee/Features/Compile/CompileManager.coffee
app/coffee/router.coffee
app/views/project/editor/pdf.jade
public/coffee/ide/pdf/controllers/PdfController.coffee
public/stylesheets/app/editor/pdf.less

add stop compile button to send 'stop' request to clsi, fetch logs on stop and timeout

add support for stopping compile

---

app/coffee/Features/Project/ProjectController.coffee
public/stylesheets/app/editor.less

This PR only adds (and namespaces) the styles for the two variants:
- Control (default) is the existing one;
- "Button" is the new alternative.
Mark-up and integration with A|B testing framework is done at the references search module.

A|B test for bib search pop-up

---

app/coffee/Features/Project/ProjectEntityHandler.coffee

prevent user creating folders which don't map to correct location on clsi

add file path check on element names

---

app/views/project/editor/header.jade
app/views/project/editor/track-changes.jade
public/coffee/ide.coffee
public/coffee/ide/track-changes/TrackChangesManager.coffee
public/coffee/ide/track-changes/controllers/TrackChangesDiffController.coffee
public/coffee/ide/track-changes/controllers/TrackChangesListController.coffee
public/stylesheets/app/editor/track-changes.less

This PR adds a a few extra events which should aid us get a better picture of feature discovery and usage (particularly, track changes).
A quick UI workaround was also added to try to prevent multiple "restores" of a given deleted file.

Track feature discovery

---

app/views/project/editor/chat.jade
public/coffee/filters/wrapLongWords.coffee
public/coffee/ide/chat/index.coffee
public/stylesheets/app/editor/chat.less

Add an Angular filter which will wrap large words in a `span` with a class to word-break anywhere.

Wrap long words chat

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/views/project/editor/pdf.jade
public/coffee/ide/editor/EditorManager.coffee
public/coffee/ide/editor/directives/aceEditor/cursor-position/CursorPositionManager.coffee
public/coffee/ide/human-readable-logs/HumanReadableLogs.coffee
public/coffee/ide/human-readable-logs/HumanReadableLogsRules.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee

Enable chktex under a recompile menu option for "syntax check"

Enable chktex

---

app/coffee/Features/Authentication/AuthenticationController.coffee
app/coffee/Features/User/UserRegistrationHandler.coffee
test/UnitTests/coffee/Authentication/AuthenticationControllerTests.coffee
test/UnitTests/coffee/User/UserRegistrationHandlerTests.coffee

Add tracking code for user registration and logins.

Track signup and login

---

app/coffee/Features/Compile/CompileController.coffee
app/views/beta_program/opt_in.jade
app/views/project/editor/pdf.jade
public/coffee/ide/editor/EditorManager.coffee
public/coffee/ide/editor/directives/aceEditor/cursor-position/CursorPositionManager.coffee
public/coffee/ide/pdf/controllers/PdfController.coffee

Turn on chktex to run in background for all users
Improve cursor click on error and display of log files.

Roll out chktex

---

app/coffee/Features/Subscription/RecurlyWrapper.coffee
app/coffee/Features/Subscription/SubscriptionController.coffee
app/views/subscriptions/edit-billing-details.jade
public/coffee/main/subscription-dashboard.coffee
test/UnitTests/coffee/Subscription/RecurlyWrapperTests.coffee

- add error handling to SubscriptionController
- add better logging info to catch the "plan_code is undefined" error
- when checking if an account exists in recurly for a user, and a 404 is an expected response, suppress error logging on 404.

Pr subscription improvements

---

Gruntfile.coffee
app/views/project/editor/pdf.jade
public/coffee/ide/pdf/controllers/PdfController.coffee
public/stylesheets/app/editor/pdf.less

Enable compile check for beta users

Compile check

---

app/coffee/Features/Collaborators/CollaboratorsInviteController.coffee
app/coffee/Features/Collaborators/CollaboratorsInviteHandler.coffee
app/coffee/Features/Collaborators/CollaboratorsRouter.coffee
app/views/project/invite/show.jade
app/views/project/list/notifications.jade
public/coffee/ide/share/controllers/ShareProjectModalController.coffee
public/coffee/main/project-list/notifications-controller.coffee
test/UnitTests/coffee/Collaborators/CollaboratorsInviteControllerTests.coffee
test/UnitTests/coffee/Collaborators/CollaboratorsInviteHandlerTests.coffee

Ja invite emails once

---

app/views/project/editor/file-tree.jade
public/coffee/ide.coffee
public/coffee/ide/file-tree/controllers/FileTreeController.coffee
public/coffee/ide/file-tree/controllers/FileTreeEntityController.coffee

Requires the following translations:
"files_cannot_include_invalid_characters": "Files cannot include '*' or '/' characters",
"invalid_file_name": "Invalid File Name"

Don't allow files to be created with / or * characters

---

Gruntfile.coffee
app/views/project/editor.jade
app/views/user/settings.jade
public/coffee/ide/editor/directives/aceEditor.coffee
public/js/ace/mode-latex.js
public/js/ace/worker-latex.js

Copied the new latex mode into the existing ace directory, so no need to upgrade ace.

Ace syntax validator minimal change

---

app/views/project/editor/header.jade
public/coffee/ide.coffee
public/stylesheets/app/editor/toolbar.less

This PR adds an AB test to determine the impact (in feature discoverability) of using labels in header items. Conversions are registered in Sixpack (overall) and Metabase (with extra granularity).
AB test should only consider newly-registered users.

AB test labels

---

app/coffee/Features/Project/ProjectController.coffee
app/coffee/Features/User/UserController.coffee
app/coffee/models/User.coffee
app/views/project/editor/editor.jade
app/views/project/editor/left-menu.jade
public/coffee/ide/editor/directives/aceEditor.coffee
public/coffee/ide/settings/controllers/SettingsController.coffee

this adds the menu option "Code check" in the editor

add left menu for syntax validator

---

Gruntfile.coffee
app/coffee/Features/Project/ProjectController.coffee
app/coffee/infrastructure/ExpressLocals.coffee
app/coffee/infrastructure/PackageVersions.coffee
app/views/layout.jade
app/views/project/editor.jade
public/coffee/filters/formatDate.coffee
public/coffee/ide/track-changes/TrackChangesManager.coffee
public/coffee/libs.coffee

Put all client package versions (pdfjs, moment and in future, ace) into a module.

Support package versions

---

app/views/layout.jade
app/views/subscriptions/edit-billing-details.jade
app/views/subscriptions/new.jade

Fixes broken requirejs loading on subscription pages

provide default requirejs config

---

app/views/layout.jade
app/views/project/editor.jade
app/views/subscriptions/edit-billing-details.jade
app/views/subscriptions/new.jade

removes the need to suppressDefaultJs

use separate jade template block for requirejs

---

public/stylesheets/app/project-list.less

Prevent overflowing project names.

---

public/coffee/ide/editor/directives/aceEditor.coffee
public/js/ace-1.2.5/mode-latex.js
public/js/ace-1.2.5/worker-latex.js

minor fixes for syntax validator

syntax validator fixes

---

public/coffee/ide/connection/ConnectionManager.coffee

use the new events connectionAccepted and connectionRejected to determine if we have a valid connection to the server.

wait for confirmation before sending joinProject

---

public/coffee/ide/connection/ConnectionManager.coffee
public/coffee/ide/editor/Document.coffee
public/coffee/ide/editor/EditorManager.coffee
public/coffee/ide/editor/ShareJsDoc.coffee

enable the saving indicator for the case where inflightOp is null but pendingOp is not (occurs when the user types after a disconnection)

fix saving indicator

---

app/coffee/infrastructure/ExpressLocals.coffee
app/coffee/infrastructure/Modules.coffee
app/coffee/infrastructure/Server.coffee
npm-shrinkwrap.json
package.json

- make it possible to add routes without Csrf protection from module routers (essential for the saml callback)
- add saml dependency
- have saml count as an external auth source

Sk passport saml

---

app/views/project/editor/header.jade
public/coffee/ide.coffee
public/stylesheets/app/editor/toolbar.less

Removes the header labels AB test, both from mark-up and JS, picking up "labels" as the winner. Also adds some responsive behaviour to the labels (hidden up to 768px).

PR Wrap header labels AB test

---

app/coffee/Features/Authentication/AuthenticationController.coffee
app/coffee/Features/Authorization/AuthorizationMiddlewear.coffee
app/coffee/Features/Subscription/SubscriptionController.coffee
app/coffee/Features/User/UserPagesController.coffee
app/views/subscriptions/plans.jade
app/views/user/login.jade
app/views/user/register.jade
test/UnitTests/coffee/Authentication/AuthenticationControllerTests.coffee
test/UnitTests/coffee/User/UserPagesControllerTests.coffee
test/acceptance/coffee/ProjectInviteTests.coffee

Use session for post-login redirect

Sk post login redirect

---

public/coffee/ide/editor/directives/aceEditor.coffee
public/js/ace-1.2.5/mode-latex_beta.js
public/js/ace-1.2.5/snippets/latex_beta.js
public/js/ace-1.2.5/worker-latex_beta.js

from our ace commit 21dde1e5f104b02e19534e56d7eb2dbd3a950db9

update latex syntax checker to include mathmode

---

public/js/ace-1.2.5/worker-latex_beta.js

from our ace commit 442a1c522c58b1e511d2fd2c6f03909488d41e60
https://github.com/sharelatex/ace/compare/21dde1e5f104b02e19534e56d7eb2dbd3a950db9...sharelatex:442a1c522c58b1e511d2fd2c6f03909488d41e60

math mode syntax checking improvements

---

app/coffee/Features/Email/EmailBuilder.coffee
public/coffee/directives/asyncForm.coffee

- Add a new 'testEmail' email type
- add `on-success` and `on-error` optional callbacks to async-form

Sk launchpad

---

app/coffee/Features/SystemMessages/SystemMessageManager.coffee

bring system message checks down to 20 secs

---

app/views/project/editor/review-panel.pug
public/coffee/ide/review-panel/directives/addCommentEntry.coffee
public/stylesheets/app/editor/review-panel.less

* Don't submit on cancel
* Center loading indicator when review panel is open

Track changes bug fixes

---

app/coffee/Features/Blog/BlogHandler.coffee

don't add /blog to the start of blog urls in annoucements

---

app/views/project/editor/editor.pug
app/views/project/editor/review-panel.pug
public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee
public/coffee/ide/review-panel/directives/addCommentEntry.coffee
public/stylesheets/app/editor/review-panel.less

Still WIP!
This PR changes the behaviour on text selection: instead of showing the whole mini-review panel just to provide the "add comment" mechanism, we have a smaller button (top-right corner of the editor).

New "add comment" button

---

app/coffee/Features/Project/ProjectApiController.coffee
app/coffee/Features/Project/ProjectDetailsHandler.coffee
test/UnitTests/coffee/Project/ProjectApiControllerTests.coffee
test/UnitTests/coffee/Project/ProjectDetailsHandlerTests.coffee

if the project does not exist there is an exception when accessing project.owner_ref

fix unhandled exception in ProjectDetailsHandler

---

public/js/ace-1.2.5/worker-latex.js

pulled from our ace repository https://github.com/sharelatex/ace
commit baeb9aff561d048b8a839683261ffdf149ecd4ef
the commit and test are at 
https://github.com/sharelatex/ace/commit/6901937b1fe9bbe887640b31266cd298f11222ef

handle the \feynmandiagram command in code check

---

app/views/project/list/project-list.pug
app/views/project/list/side-bar.pug
public/coffee/directives/selectAll.coffee
public/coffee/main/project-list/project-list.coffee
public/coffee/main/project-list/tag-controllers.coffee
public/stylesheets/app/project-list.less

This PR adds some improvements to the projects list page:
* Filtering options are now persisted in local storage
* A new filter for viewing untagged projects was added
* Also added a small "x" button near each tag in the project list, allowing inline tag removal
* Made the whole project row clickable (to select the project)

Project list improvements

---

app/coffee/Features/Chat/ChatController.coffee

Calling sync functions inside async can trigger the node max stack size.
Instead, build up our unique list of ids in advance, so we only call a
method in async for each user we actually need to look up, asynchronously.
Then use all the cached values synchronously afterwards.

Don't call sync functions inside async

---

app/views/project/editor/editor.pug
public/coffee/ide.coffee
public/coffee/ide/review-panel/controllers/ReviewPanelController.coffee

* Create an explicit watcher to control the mini RP visibility and use it to trigger Ace's resizing logic;
* Consolidate the two existing "review panel open" watchers into a single one.

Review panel relayout

---

app/coffee/Features/Errors/ErrorController.coffee
app/coffee/infrastructure/Server.coffee

only render the html for web errors, not api errors

use a separate error handler for api router errors

---

public/coffee/ide/editor/directives/aceEditor/auto-complete/AutoCompleteManager.coffee

Support variants of `\ref{}`

---

app/coffee/Features/Errors/ErrorController.coffee
app/coffee/infrastructure/Server.coffee
app/coffee/router.coffee

allow separate processes for web and api routers

split web and web api

---

public/stylesheets/app/editor/left-menu.less

This PR adds:
* A flex-based layout to allow better handling of settings with large labels;
* A small visual separator between settings.

Add a separator and better handling of line-breaks in settings.

---

app/coffee/Features/Authentication/AuthenticationManager.coffee
config/settings.defaults.coffee
public/coffee/directives/asyncForm.coffee
test/UnitTests/coffee/Authentication/AuthenticationManagerTests.coffee

- Check minimum password lengths
- Set default policy to 6-128 chars

Enforce stricter password policy.

---

app/coffee/Features/Compile/ClsiManager.coffee
app/coffee/Features/Compile/ClsiStateManager.coffee
app/coffee/Features/Compile/CompileController.coffee
app/coffee/Features/Compile/CompileManager.coffee
app/coffee/Features/DocumentUpdater/DocumentUpdaterHandler.coffee
app/coffee/Features/Project/ProjectEntityHandler.coffee
app/views/beta_program/opt_in.pug
public/coffee/ide/pdf/controllers/PdfController.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee
test/UnitTests/coffee/Compile/ClsiStateManagerTests.coffee
test/UnitTests/coffee/Compile/CompileManagerTests.coffee
test/UnitTests/coffee/DocumentUpdater/DocumentUpdaterHandlerTests.coffee
test/UnitTests/coffee/Project/ProjectEntityHandlerTests.coffee

keep project state in redis, try to compile incrementally when possible (state hasn't changed), otherwise retry with a full compile
Outstanding tasks:

compile from redis

---

Gruntfile.coffee
app/coffee/models/Project.coffee
npm-shrinkwrap.json
package.json

Goes with https://github.com/sharelatex/overleaf-auth-web-module/pull/1

Update Project schema for overleaf imports

---

app/coffee/Features/Collaborators/CollaboratorsHandler.coffee
app/coffee/Features/User/UserGetter.coffee
app/coffee/infrastructure/mongojs.coffee
app/coffee/models/UserStub.coffee
test/UnitTests/coffee/Collaborators/CollaboratorsHandlerTests.coffee

Goes with https://github.com/sharelatex/overleaf-auth-web-module/pull/2

Add in UserStub model and support in collaborators view

---

app/coffee/Features/Collaborators/CollaboratorsHandler.coffee
test/acceptance/coffee/ProjectFeaturesTests.coffee
test/acceptance/coffee/helpers/User.coffee

Fixes a bug where project features were not applied properly,
and instead fell back to the free-account defaults.

Load user features alongside id and email.

---

app/coffee/Features/InactiveData/InactiveProjectController.coffee

convert request parameter from string to number

avoid error when passing as limit in mongo query

---

app/coffee/Features/Compile/ClsiManager.coffee
test/UnitTests/coffee/Compile/ClsiManagerTests.coffee

This is just the proof of concept - not tested yet!

fix root doc in incremental compile

---

app/coffee/models/Project.coffee

Add needed fields for Overleaf integration

Include OL tokens in project schema

---

public/coffee/ide/editor/directives/aceEditor/auto-complete/AutoCompleteManager.coffee
public/coffee/ide/editor/directives/aceEditor/auto-complete/Helpers.coffee

Refactor out common code in AutocompleteManager.
